#!/usr/bin/env python3

import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.realpath(__file__))

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('conffile', nargs='?', default=os.path.join(HERE, 'conf.yml'),
                        help='defaults to conf.yml')
    args = parser.parse_args()

    if not os.path.isfile(args.conffile):
        sys.stderr.write(f'{conffile} does not exist or is a directory')
        sys.exit(1)

    os.environ['CONFFILE'] = args.conffile
    os.environ['PYTHON'] = sys.executable

    import conf
    script_name = 'build-production' if conf.production else 'build-development'
    script_path = os.path.join(HERE, 'tools', script_name)
    args = [
        args.conffile,
        conf.buildpath,
        '1' if conf.local_images else '0',
        conf.ga_tracking_id if conf.enable_ga else ''
    ]
    subprocess.run([script_path, *args])

if __name__ == '__main__':
    main()
